# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
jobs:
- job: 'linux_build'
  displayName: 'Linux Builds'
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 90
  strategy:
    maxParallel: 4
    matrix:
      max_det_orb_64:
        F_COMPILER: 'gfortran'
        APT_INSTALL: 'gfortran'
        C_COMPILER: 'gcc'
        CXX_COMPILER: 'g++'
        PYTHON_VER: '3.7'
        BUILD_TYPE: 'debug'
        MAX_DET_ORB: 64

#     max_det_orb_128:
#       F_COMPILER: 'gfortran'
#       APT_INSTALL: 'gfortran'
#       C_COMPILER: 'gcc'
#       CXX_COMPILER: 'g++'
#       PYTHON_VER: '3.7'
#       BUILD_TYPE: 'debug'
#       MAX_DET_ORB: 128

  steps:
  - bash: |
      [[ "${APT_REPOSITORY}" ]] && echo "Add Repo ${APT_REPOSITORY}" && sudo add-apt-repository "${APT_REPOSITORY}"
      sudo apt-get update
      sudo apt-get install ${APT_INSTALL}
    displayName: "Apt-Get Packages"

  - bash: |
      echo "" && echo "Ubuntu"
      lsb_release -a

      echo "" && echo "Uname:"
      uname -a

      echo "" && echo "Free:"
      free -m

      echo "" && echo "df:"
      df -h

      echo "" && echo "Ulimit:"
      ulimit -a

      echo "" && echo "Nprocs:"
      getconf _NPROCESSORS_ONLN

      echo "C Ver:"
      ${C_COMPILER} --version

      echo "CXX Ver:"
      ${CXX_COMPILER} --version

      echo "F Ver:"
      ${F_COMPILER} --version
    displayName: 'Setup Information'

  - bash: |
      mkdir -p build/forte
      cp -r !(build) build/forte/
      ls build/forte/
    displayName: 'Copy Forte Source'

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda config --set always_yes yes
    displayName: 'Add Conda to PATH'

  - bash: |
      conda create -q \
        -n p4env \
        python=$PYTHON_VER \
        psi4/label/dev::gau2grid=2 \
        psi4/label/dev::libint2 \
        psi4/label/dev::libxc \
        psi4/label/dev::ambit \
        psi4/label/dev::chemps2 \
        psi4/label/dev::dkh \
        psi4/label/dev::gdma \
        psi4/label/dev::pcmsolver \
        psi4/label/dev::simint \
        psi4/label/dev::dftd3 \
        psi4/label/dev::gcp \
        psi4/label/dev::resp \
        psi4/label/dev::pycppe \
        psi4/label/dev::pylibefp \
        psi4/label/dev::snsmp2 \
        psi4/label/dev::fockci \
        psi4/label/dev::mp2d \
        blas=*=mkl \
        mkl-include \
        networkx \
        pytest \
        eigen \
        mpfr \
        pytest-xdist \
        conda-forge::qcelemental \
        conda-forge::qcengine \
        conda-forge::pymdi \
        adcc::adcc
      source activate p4env
      conda install -c conda-forge \
        cmake \
        hdf5 \
        boost \
        mkl-devel \
        pybind11 \
        pytest \
        pytest-xdist \
        codecov \
        lcov \
        pytest-cov
      which python
      pip install git+https://github.com/i-pi/i-pi.git@master-py3
      conda list
    displayName: 'Configure Environment'

  - bash: |
      source activate p4env
      which cmake
      cmake --version
      echo "Agent.BuildDirectory:" $(Agent.BuildDirectory)
      echo "Build.SourcesDirectory:" $(Build.SourcesDirectory)
      echo "Now at directory:" $PWD
      mkdir -p build/psi4bin
      cd build
      git clone https://github.com/psi4/psi4.git psi4
      cd psi4
      echo "Now at directory (before Psi4 cmake):" $PWD
      cmake -H. -Bobjdir \
        -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
        -DCMAKE_C_COMPILER=${C_COMPILER} \
        -DCMAKE_Fortran_COMPILER=${F_COMPILER} \
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -Dpsi4_CXX_STANDARD=17 \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} \
        -DPYTHON_EXECUTABLE=${CONDA_PREFIX}/bin/python \
        -DCMAKE_CXX_FLAGS=-DPYBIND11_CPP17 \
        -DCMAKE_INSTALL_PREFIX=$(Build.SourcesDirectory)/build/psi4bin
      cd objdir
      echo "Now at directory (Psi4 objdir):" $PWD
      make -j2
      echo "Now install Psi4 at: $(Build.SourcesDirectory)/build/psi4bin"
      make install
    displayName: 'Build Psi4 Manually'

  - bash: |
      source activate p4env
      echo "Conda path: ${CONDA_PREFIX}"
      echo "Python: $(which python)"
      python -V
      export PATH="$(Build.SourcesDirectory)/build/psi4bin/bin:$PATH"
      psi4 --version
      psi4 --plugin-compile
#     PYBIND_INCLUDE=$(python -m pybind11 --includes)
#     echo "PYBIND_INCLUDE:" $PYBIND_INCLUDE
      cd build/forte
      cmake -H. -B. \
        -C$(Build.SourcesDirectory)/build/psi4bin/share/cmake/psi4/psi4PluginCache.cmake \
        -Dambit_DIR=${CONDA_PREFIX}/share/cmake/ambit \
        -DCMAKE_CXX_STANDARD=17 \
        -DPYTHON_EXECUTABLE="${CONDA_PREFIX}/bin/python" \
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -DENABLE_CODECOV=ON \
        -DCMAKE_CXX_FLAGS=-DPYBIND11_CPP17 \
        -DMAX_DET_ORB=${MAX_DET_ORB}
    displayName: 'Configure Build'

  - bash: |
      source activate p4env
      cd build/forte
      make -j2 VERBOSE=1
    displayName: 'Build Forte'

  - bash: |
      source activate p4env
      export PYTHONPATH="$(Build.SourcesDirectory)/build/forte:$PYTHONPATH"
      echo "PYTHONPATH: $PYTHONPATH"
      export PATH="$(Build.SourcesDirectory)/build/psi4bin/bin:$PATH"
      echo "PATH: $PATH"

      bash tools/forte_codecov
      if [ $MAX_DET_ORB -ge 128 ]; then
        cd tests/large_det
        python run_forte_tests.py --bw --failed_dump
      fi
      cd $(Build.SourcesDirectory)/tests/pytest
      pytest
    displayName: 'Run Forte tests'
